### ISSUE TITLE
请问怎么将关键点对应关键点名称

### ISSUE THREAD

**Issue by liujb1314** [guojin-yan/Csharp_and_OpenVINO_deploy_PP-TinyPose#2]
![image](https://user-images.githubusercontent.com/10348926/225508160-ce8246a7-b557-4fbc-adc2-fb910eb719be.png)
已经成功运行，并得到关键点预测结果，请问如何把这些预测结果与名称对应起来，比如眼睛、手肘

**Comment by guojin-yan** [comment]
这个模型使用的是飞桨提供的训练模型，他这个模型训练使用的是COCO keypoint 数据集，按照训练集的组成，他这个输出的顺序是和训练一致的，所以输出的数组是按照下面17个关键点排列的。[x, y, score]
COCO keypoint Description:
    0: "Nose",
    1: "Left Eye",
    2: "Right Eye",
    3: "Left Ear",
    4: "Right Ear",
    5: "Left Shoulder,
    6: "Right Shoulder",
    7: "Left Elbow",
    8: "Right Elbow",
    9: "Left Wrist",
    10: "Right Wrist",
    11: "Left Hip",
    12: "Right Hip",
    13: "Left Knee",
    14: "Right Knee",
    15: "Left Ankle",
    16: "Right Ankle"

具体可以查看飞桨文档：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/configs/keypoint/tiny_pose

**Comment by liujb1314** [comment]
> 关键点预测结果，请问如何把这些预测结果与名称对

十分感谢，您帮了大忙了。

**Comment by liujb1314** [comment]
十分感谢，您帮了大忙了。
